# Generated by Django 5.2.6 on 2025-10-10 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conversion', models.CharField(choices=[('word_to_pdf', 'Word a PDF'), ('pdf_to_word', 'PDF a Word')], max_length=20)),
                ('archivo_original', models.FileField(upload_to='conversiones/originales/')),
                ('archivo_convertido', models.FileField(blank=True, null=True, upload_to='conversiones/convertidos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('usar_ocr', models.BooleanField(default=False, help_text='Usar OCR para extraer texto de imágenes')),
                ('error_mensaje', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajo de Conversión',
                'verbose_name_plural': 'Trabajos de Conversión',
                'ordering': ['-created_at'],
            },
        ),
    ]
