# Generated by Django 5.2.6 on 2025-10-09 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_moderado_at_post_moderado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='foro',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foro',
            name='es_privado',
            field=models.BooleanField(default=False, help_text='Si es privado, solo estudiantes de la carrera pueden ver el foro'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen adjunta (requiere aprobación de administrador)', null=True, upload_to='forum/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_aprobada',
            field=models.BooleanField(default=False, help_text='True si la imagen fue aprobada por un administrador'),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentario'), ('encuesta', 'Encuesta'), ('imagen', 'Imagen'), ('otro', 'Otro')], default='comentario', help_text='Tipo de publicación', max_length=20),
        ),
        migrations.CreateModel(
            name='OpcionEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('votos', models.PositiveIntegerField(default=0)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(limit_choices_to={'tipo': 'encuesta'}, on_delete=django.db.models.deletion.CASCADE, related_name='opciones_encuesta', to='forum.post')),
            ],
            options={
                'verbose_name': 'Opción de Encuesta',
                'verbose_name_plural': 'Opciones de Encuesta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='VotoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_usuarios', to='forum.opcionencuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_encuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto en Encuesta',
                'verbose_name_plural': 'Votos en Encuestas',
                'unique_together': {('opcion', 'usuario')},
            },
        ),
    ]
