# Generated by Django 5.2.6 on 2025-10-10 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_foro_created_at_foro_descripcion_foro_es_privado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foro',
            options={'ordering': ['carrera', 'titulo']},
        ),
    ]
