# Generated by Django 5.2.6 on 2025-10-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_foro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enlace_url',
            field=models.URLField(blank=True, help_text='URL asociada al post cuando es de tipo enlace', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo adjunto para publicaciones de tipo archivo', null=True, upload_to='forum/files/'),
        ),
    ]


