# Generated by Django 5.2.6 on 2025-10-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_enlace_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente', max_length=20),
        ),
    ]


