# Generated by Django 5.2.7 on 2025-10-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_postreporte_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentario'), ('encuesta', 'Encuesta'), ('imagen', 'Imagen'), ('enlace', 'Enlace'), ('archivo', 'Archivo'), ('otro', 'Otro')], default='comentario', help_text='Tipo de publicación', max_length=20),
        ),
    ]
