# Generated by Django 5.2.8 on 2025-11-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_post_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_aprobada',
            field=models.BooleanField(default=True, help_text='True si la imagen fue aprobada por un administrador'),
        ),
    ]
