# Generated by Django 5.2.8 on 2025-11-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_post_imagen_aprobada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado'), ('post_eliminado', 'Post Eliminado')], default='pendiente', max_length=20),
        ),
    ]
