# Generated by Django 5.2.6 on 2025-09-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorridopaso',
            name='imagen_360_thumbnail',
            field=models.URLField(blank=True, help_text='Thumbnail de la imagen 360°'),
        ),
        migrations.AddField(
            model_name='recorridopaso',
            name='imagen_360_url',
            field=models.URLField(blank=True, help_text='URL de imagen 360° para Street View personalizado'),
        ),
        migrations.AddField(
            model_name='recorridopaso',
            name='streetview_fov',
            field=models.FloatField(default=90, help_text='Campo de visión (10-120 grados)'),
        ),
        migrations.AddField(
            model_name='recorridopaso',
            name='streetview_heading',
            field=models.FloatField(default=0, help_text='Dirección de la cámara en grados (0-360)'),
        ),
        migrations.AddField(
            model_name='recorridopaso',
            name='streetview_pitch',
            field=models.FloatField(default=0, help_text='Inclinación de la cámara (-90 a 90)'),
        ),
        migrations.AddField(
            model_name='recorridopaso',
            name='usar_streetview',
            field=models.BooleanField(default=False, help_text='Usar Street View personalizado en lugar de imagen estática'),
        ),
    ]
