# Generated by Django 5.2.5 on 2025-09-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BienestarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carrera", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("kine", "Kinesiología"), ("psico", "Psicología")],
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido_md", models.TextField()),
                ("media_url", models.URLField(blank=True)),
            ],
        ),
    ]
