# Generated by Django 5.2.8 on 2025-11-13 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bienestaritem',
            options={'ordering': ['orden', 'tipo', 'categoria', 'titulo'], 'verbose_name': 'Contenido de Bienestar', 'verbose_name_plural': 'Contenidos de Bienestar'},
        ),
        migrations.AddField(
            model_name='bienestaritem',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está visible para los estudiantes'),
        ),
        migrations.AddField(
            model_name='bienestaritem',
            name='categoria',
            field=models.CharField(choices=[('postura', 'Postura y Ergonomía'), ('oculares', 'Cuidado Visual'), ('estiramientos', 'Estiramientos'), ('pausas', 'Pausas Activas'), ('estres', 'Manejo del Estrés'), ('ansiedad', 'Ansiedad'), ('concentracion', 'Concentración'), ('descanso', 'Descanso y Sueño'), ('alimentacion', 'Alimentación Saludable'), ('hidratacion', 'Hidratación'), ('energia', 'Energía y Rendimiento')], default='estiramientos', help_text='Categoría específica del contenido', max_length=20),
        ),
        migrations.AddField(
            model_name='bienestaritem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='bienestaritem',
            name='descripcion_corta',
            field=models.CharField(blank=True, help_text='Descripción breve para preview', max_length=300),
        ),
        migrations.AddField(
            model_name='bienestaritem',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estimada en minutos', null=True),
        ),
        migrations.AddField(
            model_name='bienestaritem',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de visualización (menor primero)'),
        ),
        migrations.AddField(
            model_name='bienestaritem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bienestaritem',
            name='carrera',
            field=models.CharField(help_text='Nombre de la carrera (ej: Ingeniería en Informática)', max_length=150),
        ),
        migrations.AlterField(
            model_name='bienestaritem',
            name='contenido_md',
            field=models.TextField(help_text='Contenido en formato Markdown'),
        ),
        migrations.AlterField(
            model_name='bienestaritem',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL de video o imagen complementaria'),
        ),
        migrations.AlterField(
            model_name='bienestaritem',
            name='tipo',
            field=models.CharField(choices=[('fisico', 'Bienestar Físico'), ('mental', 'Bienestar Mental'), ('nutricional', 'Nutrición')], help_text='Tipo de bienestar', max_length=15),
        ),
        migrations.AlterField(
            model_name='bienestaritem',
            name='titulo',
            field=models.CharField(help_text='Título del recurso', max_length=200),
        ),
        migrations.AddIndex(
            model_name='bienestaritem',
            index=models.Index(fields=['carrera', 'tipo'], name='wellbeing_b_carrera_639fde_idx'),
        ),
        migrations.AddIndex(
            model_name='bienestaritem',
            index=models.Index(fields=['activo', 'orden'], name='wellbeing_b_activo_015af1_idx'),
        ),
    ]
