# Generated by Django 5.2.8 on 2025-11-11 13:53

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-created_at'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(default='General', help_text='Categoria: Programacion, Diseño, Matematicas, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 40 horas, 3 meses, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='email_contacto',
            field=models.EmailField(blank=True, help_text='Email de contacto (solo para anuncios personales)', max_length=254),
        ),
        migrations.AddField(
            model_name='curso',
            name='es_gratuito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen del curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Hibrido')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('todos', 'Todos los niveles')], default='todos', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Precio en pesos chilenos. Dejar vacio para gratuito', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='curso',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Telefono de contacto (solo para anuncios personales)', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('personal', 'Clases Privadas / Tutorias'), ('externo', 'Curso Externo')], default='externo', help_text='Tipo de publicacion', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='visualizaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(help_text='Descripcion detallada'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='etiquetas',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(help_text='Fecha de inicio del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(help_text='Titulo del curso o clase', max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='url',
            field=models.URLField(blank=True, help_text='URL del curso (para cursos externos) o plataforma de contacto'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['-created_at'], name='otec_curso_created_2bc1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['tipo'], name='otec_curso_tipo_e12e89_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['categoria'], name='otec_curso_categor_52c4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['visible'], name='otec_curso_visible_124bc0_idx'),
        ),
    ]
