# Generated by Django 5.2.8 on 2025-11-20 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0002_alter_curso_options_curso_categoria_curso_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('personal', 'Clases Privadas / Tutorias'), ('externo', 'Curso Externo'), ('video', 'Curso con Videos')], default='externo', help_text='Tipo de publicacion', max_length=20),
        ),
        migrations.CreateModel(
            name='ClaseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_clase', models.PositiveIntegerField(help_text='Número de la clase (1, 2, 3, etc.)')),
                ('titulo', models.CharField(help_text='Título de la clase', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la clase')),
                ('video', models.FileField(help_text='Archivo de video de la clase', upload_to='cursos/videos/')),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, help_text='Duración del video en segundos (opcional)', null=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (para ordenar clases)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(help_text='Curso al que pertenece esta clase', on_delete=django.db.models.deletion.CASCADE, related_name='clases_video', to='otec.curso')),
            ],
            options={
                'verbose_name': 'Clase con Video',
                'verbose_name_plural': 'Clases con Video',
                'ordering': ['curso', 'orden', 'numero_clase'],
                'indexes': [models.Index(fields=['curso', 'orden'], name='otec_clasev_curso_i_6e7e7e_idx'), models.Index(fields=['curso', 'numero_clase'], name='otec_clasev_curso_i_b452b5_idx')],
                'unique_together': {('curso', 'numero_clase')},
            },
        ),
    ]
