# Generated by Django 5.2.8 on 2025-11-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0003_alter_curso_tipo_clasevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin (DEPRECATED)', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio del curso (DEPRECATED)', null=True),
        ),
    ]
