# Generated by Django 5.2.6 on 2025-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_es_estudiante_gmail_user_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='ID único de Google', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True si el email está verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, help_text='URL de la foto de perfil de Google'),
        ),
    ]
