# Generated by Django 5.2.6 on 2025-10-09 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_google_id_user_is_verified_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera_anterior', models.CharField(max_length=150)),
                ('carrera_nueva', models.CharField(max_length=150)),
                ('razon', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_carrera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de Carrera',
                'verbose_name_plural': 'Cambios de Carrera',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
