# Generated by Django 5.2.6 on 2025-10-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cambiocarrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='Codigo de verificacion de 6 digitos', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='True si el email fue verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, help_text='Codigo de recuperacion de contraseña', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_file',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='semestre',
            field=models.PositiveIntegerField(default=1, help_text='Semestre actual del estudiante'),
        ),
    ]
