# Generated by Django 5.2.7 on 2025-11-05 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_intentado', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('razon_fallo', models.CharField(blank=True, help_text='Razón si el login falló', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Login',
                'verbose_name_plural': 'Registros de Login',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='accounts_lo_usuario_cb8a7a_idx'), models.Index(fields=['email_intentado', '-created_at'], name='accounts_lo_email_i_43fb2b_idx'), models.Index(fields=['estado', '-created_at'], name='accounts_lo_estado_7c95fe_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_lo_ip_addr_a6aa26_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name_intentado', models.CharField(blank=True, max_length=150)),
                ('career_intentada', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('pendiente_verificacion', 'Pendiente Verificación')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('razon_fallo', models.CharField(blank=True, help_text='Razón si el registro falló', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Registro',
                'verbose_name_plural': 'Registros de Registro',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='accounts_re_usuario_13db1a_idx'), models.Index(fields=['email', '-created_at'], name='accounts_re_email_2294c0_idx'), models.Index(fields=['estado', '-created_at'], name='accounts_re_estado_e8c062_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registro', 'Registro'), ('verificacion_email', 'Verificación de Email'), ('cambio_password', 'Cambio de Contraseña'), ('recuperacion_password', 'Recuperación de Contraseña'), ('actualizacion_perfil', 'Actualización de Perfil'), ('cambio_carrera', 'Cambio de Carrera'), ('creacion_post', 'Creación de Post'), ('creacion_comentario', 'Creación de Comentario'), ('voto_post', 'Voto en Post'), ('creacion_producto', 'Creación de Producto'), ('creacion_proyecto', 'Creación de Proyecto'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='accounts_us_usuario_cae598_idx'), models.Index(fields=['tipo', '-created_at'], name='accounts_us_tipo_e00696_idx'), models.Index(fields=['created_at'], name='accounts_us_created_9643e0_idx')],
            },
        ),
    ]
