# Generated by Django 5.2.6 on 2025-09-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_foro', models.BooleanField(default=True)),
                ('recibir_market', models.BooleanField(default=True)),
                ('recibir_portfolio', models.BooleanField(default=True)),
                ('recibir_campus', models.BooleanField(default=True)),
                ('recibir_polls', models.BooleanField(default=True)),
                ('recibir_academic', models.BooleanField(default=True)),
                ('recibir_system', models.BooleanField(default=True)),
                ('frecuencia_email', models.CharField(choices=[('inmediato', 'Inmediato'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('nunca', 'Nunca')], default='inmediato', max_length=20)),
                ('horario_inicio', models.TimeField(default='09:00')),
                ('horario_fin', models.TimeField(default='18:00')),
                ('solo_dias_laborales', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificacionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('titulo_template', models.CharField(max_length=200)),
                ('mensaje_template', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('forum', 'Foro'), ('market', 'Mercado'), ('portfolio', 'Portafolio'), ('campus', 'Campus'), ('polls', 'Encuestas'), ('academic', 'Académico'), ('system', 'Sistema')], max_length=20)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='enviada_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase de icono FontAwesome', max_length=50),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url_redirect',
            field=models.URLField(blank=True, help_text='URL a la que redirigir al hacer clic'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('forum', 'Foro'), ('market', 'Mercado'), ('portfolio', 'Portafolio'), ('campus', 'Campus'), ('polls', 'Encuestas'), ('academic', 'Académico'), ('system', 'Sistema')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='notificatio_usuario_8e0ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo', 'created_at'], name='notificatio_tipo_6e3427_idx'),
        ),
        migrations.AddField(
            model_name='notificacionconfig',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_config', to=settings.AUTH_USER_MODEL),
        ),
    ]
