# Generated by Django 5.2.7 on 2025-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemedia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del problema reportado', null=True, upload_to='reports/images/'),
        ),
        migrations.AlterField(
            model_name='reportemedia',
            name='url',
            field=models.URLField(blank=True, help_text='URL alternativa si no se sube archivo', null=True),
        ),
    ]
