# Generated by Django 5.2.6 on 2025-09-06 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0002_recorridopaso_imagen_360_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono (ej: bi-book, bi-laptop)', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url_principal', models.URLField(help_text='Enlace principal de venta', validators=[django.core.validators.URLValidator()])),
                ('tipo_enlace', models.CharField(choices=[('facebook', 'Facebook Marketplace'), ('yapo', 'Yapo.cl'), ('mercadolibre', 'MercadoLibre'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('urls_adicionales', models.JSONField(blank=True, default=list, help_text='Lista de URLs adicionales (ej: fotos, videos)')),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('og_site_name', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('vendido', 'Vendido'), ('oculto', 'Oculto')], default='borrador', max_length=20)),
                ('precio', models.DecimalField(blank=True, decimal_places=0, help_text='Precio en CLP', max_digits=10, null=True)),
                ('moneda', models.CharField(default='CLP', max_length=3)),
                ('carrera', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicado_at', models.DateTimeField(blank=True, null=True)),
                ('vendido_at', models.DateTimeField(blank=True, null=True)),
                ('visualizaciones', models.PositiveIntegerField(default=0)),
                ('clicks_enlace', models.PositiveIntegerField(default=0)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='campuses.sede')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='market.categoriaproducto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_vendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visualizaciones', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_favoritos', models.PositiveIntegerField(default=0)),
                ('total_reportes', models.PositiveIntegerField(default=0)),
                ('visualizaciones_por_campus', models.JSONField(default=dict)),
                ('visualizaciones_por_carrera', models.JSONField(default=dict)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='market.producto')),
            ],
            options={
                'verbose_name': 'Analytics de Producto',
                'verbose_name_plural': 'Analytics de Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='market.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Favorito',
                'verbose_name_plural': 'Productos Favoritos',
            },
        ),
        migrations.CreateModel(
            name='ProductoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fraude', 'Posible Fraude'), ('inapropiado', 'Contenido Inapropiado'), ('spam', 'Spam'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('resuelto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='market.producto')),
                ('reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Producto',
                'verbose_name_plural': 'Reportes de Productos',
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado', 'publicado_at'], name='market_prod_estado_37df54_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'estado'], name='market_prod_categor_120be4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['campus', 'carrera'], name='market_prod_campus__2aef9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productofavorito',
            unique_together={('usuario', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='productoreporte',
            unique_together={('producto', 'reportador')},
        ),
    ]
