# Generated by Django 5.2.7 on 2025-11-10 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='acepta_responsabilidad',
            field=models.BooleanField(default=False, help_text='El vendedor acepta la responsabilidad legal y descarga a StudentsPoint'),
        ),
        migrations.AddField(
            model_name='producto',
            name='acepta_terminos',
            field=models.BooleanField(default=False, help_text='El vendedor acepta los términos y condiciones del Marketplace'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ip_aceptacion',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_principal',
            field=models.URLField(help_text='Enlace principal de venta (OBLIGATORIO - Facebook Marketplace, Mercado Libre, etc.)', validators=[django.core.validators.URLValidator()]),
        ),
    ]
