# Generated by Django 5.2.7 on 2025-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_agregar_terminos_condiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_student_point',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text='Precio preferente ofrecido dentro de StudentsPoint (CLP)',
                max_digits=10,
                null=True,
            ),
        ),
    ]

