# Generated by Django 5.2.8 on 2025-11-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_producto_precio_student_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto subida manualmente', null=True, upload_to='market/productos/%Y/%m/'),
        ),
    ]
