# Generated by Django 5.2.8 on 2025-11-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
