# Generated by Django 5.2.8 on 2025-11-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_descripcion_opcional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoreporte',
            name='resuelto',
        ),
        migrations.AddField(
            model_name='productoreporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado'), ('producto_eliminado', 'Producto Eliminado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='productoreporte',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
