# Generated by Django 5.2.6 on 2025-09-22 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0002_recorridopaso_imagen_360_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_metricas_tiempo_real', models.BooleanField(default=True)),
                ('mostrar_reportes_recientes', models.BooleanField(default=True)),
                ('mostrar_mantenimientos_pendientes', models.BooleanField(default=True)),
                ('mostrar_alertas', models.BooleanField(default=True)),
                ('mostrar_graficos_ocupacion', models.BooleanField(default=True)),
                ('umbral_ocupacion', models.PositiveIntegerField(default=80, help_text='Umbral de ocupación para alertas (%)')),
                ('umbral_temperatura_max', models.FloatField(default=30.0, help_text='Temperatura máxima (°C)')),
                ('umbral_temperatura_min', models.FloatField(default=18.0, help_text='Temperatura mínima (°C)')),
                ('umbral_ruido', models.FloatField(default=70.0, help_text='Umbral de ruido (dB)')),
                ('recibir_alertas_email', models.BooleanField(default=True)),
                ('recibir_alertas_push', models.BooleanField(default=True)),
                ('frecuencia_alertas', models.CharField(choices=[('inmediato', 'Inmediato'), ('cada_15min', 'Cada 15 minutos'), ('cada_hora', 'Cada hora'), ('diario', 'Diario')], default='inmediato', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Dashboard',
                'verbose_name_plural': 'Configuraciones de Dashboard',
            },
        ),
        migrations.CreateModel(
            name='InfraestructuraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('biblioteca', 'Biblioteca'), ('cafeteria', 'Cafetería'), ('gimnasio', 'Gimnasio'), ('auditorio', 'Auditorio'), ('oficina', 'Oficina'), ('estacionamiento', 'Estacionamiento'), ('wifi', 'WiFi'), ('servidor', 'Servidor'), ('aire_acondicionado', 'Aire Acondicionado'), ('iluminacion', 'Iluminación'), ('otro', 'Otro')], max_length=30)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_actual', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio'), ('reparacion', 'En Reparación'), ('obsoleto', 'Obsoleto')], default='operativo', max_length=20)),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, help_text='Capacidad máxima de personas', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraestructura_items', to='campuses.sede')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infraestructura_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento de Infraestructura',
                'verbose_name_plural': 'Elementos de Infraestructura',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlertaInfraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ocupacion', 'Ocupación'), ('temperatura', 'Temperatura'), ('ruido', 'Ruido'), ('wifi', 'WiFi'), ('mantenimiento', 'Mantenimiento'), ('incidente', 'Incidente')], max_length=20)),
                ('nivel', models.CharField(choices=[('info', 'Informativa'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítica')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('valor_actual', models.FloatField(blank=True, help_text='Valor que disparó la alerta', null=True)),
                ('valor_umbral', models.FloatField(blank=True, help_text='Umbral configurado', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_resuelta', models.DateTimeField(blank=True, null=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='infrastructure_monitoring.infraestructuraitem')),
            ],
            options={
                'verbose_name': 'Alerta de Infraestructura',
                'verbose_name_plural': 'Alertas de Infraestructura',
                'ordering': ['-fecha_generada'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('mejora', 'Mejora'), ('inspeccion', 'Inspección'), ('limpieza', 'Limpieza')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('duracion_estimada_horas', models.PositiveIntegerField()),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='infrastructure_monitoring.infraestructuraitem')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento Programado',
                'verbose_name_plural': 'Mantenimientos Programados',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='MetricasInfraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True)),
                ('ocupacion_actual', models.PositiveIntegerField(default=0, help_text='Personas actualmente en el espacio')),
                ('ocupacion_promedio', models.FloatField(default=0.0, help_text='Ocupación promedio en las últimas 24h')),
                ('tiempo_uso_total', models.PositiveIntegerField(default=0, help_text='Tiempo total de uso en minutos')),
                ('temperatura', models.FloatField(blank=True, help_text='Temperatura en °C', null=True)),
                ('humedad', models.FloatField(blank=True, help_text='Humedad en %', null=True)),
                ('ruido_db', models.FloatField(blank=True, help_text='Nivel de ruido en dB', null=True)),
                ('velocidad_wifi', models.FloatField(blank=True, help_text='Velocidad WiFi en Mbps', null=True)),
                ('calificacion_satisfaccion', models.PositiveIntegerField(blank=True, help_text='Calificación de satisfacción de 1 a 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentarios', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='infrastructure_monitoring.infraestructuraitem')),
            ],
            options={
                'verbose_name': 'Métrica de Infraestructura',
                'verbose_name_plural': 'Métricas de Infraestructura',
                'ordering': ['-fecha_medicion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteInfraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('problema', 'Problema'), ('mantenimiento', 'Mantenimiento'), ('mejora', 'Mejora'), ('incidente', 'Incidente'), ('actualizacion', 'Actualización')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='abierto', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True)),
                ('imagenes', models.JSONField(blank=True, default=list, help_text='URLs de imágenes del problema')),
                ('costo_reparacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_resolucion_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='infrastructure_monitoring.infraestructuraitem')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_infraestructura', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Infraestructura',
                'verbose_name_plural': 'Reportes de Infraestructura',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
