# Generated by Django 5.2.6 on 2025-09-06 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_contrato', models.CharField(choices=[('practica', 'Práctica Profesional'), ('part_time', 'Medio Tiempo'), ('full_time', 'Tiempo Completo'), ('freelance', 'Freelance'), ('voluntariado', 'Voluntariado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actual', models.BooleanField(default=False)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('academico', 'Académico'), ('profesional', 'Profesional'), ('voluntariado', 'Voluntariado'), ('deportivo', 'Deportivo'), ('cultural', 'Cultural'), ('otro', 'Otro')], max_length=20)),
                ('fecha_obtencion', models.DateField()),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('certificado_url', models.URLField(blank=True, help_text='URL del certificado o evidencia')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['-fecha_obtencion'],
            },
        ),
        migrations.CreateModel(
            name='PortafolioAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completitud_perfil', models.FloatField(default=0.0, help_text='Porcentaje de completitud del perfil')),
                ('total_logros', models.PositiveIntegerField(default=0)),
                ('total_proyectos', models.PositiveIntegerField(default=0)),
                ('total_experiencias', models.PositiveIntegerField(default=0)),
                ('total_habilidades', models.PositiveIntegerField(default=0)),
                ('visualizaciones_pdf', models.PositiveIntegerField(default=0)),
                ('descargas_pdf', models.PositiveIntegerField(default=0)),
                ('ultima_visualizacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics de Portafolio',
                'verbose_name_plural': 'Analytics de Portafolios',
            },
        ),
        migrations.CreateModel(
            name='PortafolioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_profesional', models.CharField(blank=True, max_length=200)),
                ('resumen_profesional', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('mostrar_contacto', models.BooleanField(default=True)),
                ('mostrar_redes_sociales', models.BooleanField(default=True)),
                ('mostrar_logros', models.BooleanField(default=True)),
                ('mostrar_proyectos', models.BooleanField(default=True)),
                ('mostrar_experiencia', models.BooleanField(default=True)),
                ('mostrar_habilidades', models.BooleanField(default=True)),
                ('tema_color', models.CharField(default='#2e004f', help_text='Color principal en hexadecimal', max_length=7)),
                ('incluir_foto', models.BooleanField(default=False)),
                ('foto_url', models.URLField(blank=True)),
                ('ultima_generacion', models.DateTimeField(blank=True, null=True)),
                ('version_pdf', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Portafolio',
                'verbose_name_plural': 'Configuraciones de Portafolio',
            },
        ),
        migrations.CreateModel(
            name='PortafolioSugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('completar_perfil', 'Completar Perfil'), ('agregar_proyectos', 'Agregar Proyectos'), ('mejorar_habilidades', 'Mejorar Habilidades'), ('agregar_experiencia', 'Agregar Experiencia'), ('agregar_logros', 'Agregar Logros'), ('mejorar_descripcion', 'Mejorar Descripción')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('completada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_portafolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia de Portafolio',
                'verbose_name_plural': 'Sugerencias de Portafolio',
                'ordering': ['-prioridad', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.JSONField(default=list, help_text='Lista de tecnologías utilizadas')),
                ('estado', models.CharField(choices=[('en_desarrollo', 'En Desarrollo'), ('completado', 'Completado'), ('en_pausa', 'En Pausa'), ('cancelado', 'Cancelado')], default='en_desarrollo', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('url_repositorio', models.URLField(blank=True)),
                ('url_demo', models.URLField(blank=True)),
                ('imagenes', models.JSONField(default=list, help_text='URLs de imágenes del proyecto')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('tecnica', 'Técnica'), ('blanda', 'Blanda'), ('idioma', 'Idioma'), ('herramienta', 'Herramienta')], max_length=20)),
                ('nivel', models.PositiveIntegerField(help_text='Nivel de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('descripcion', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
    ]
