# Generated by Django 5.2.6 on 2025-09-06 02:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0002_recorridopaso_imagen_360_thumbnail_and_more'),
        ('forum', '0001_initial'),
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visualizaciones', models.PositiveIntegerField(default=0)),
                ('total_participantes', models.PositiveIntegerField(default=0)),
                ('tasa_participacion', models.FloatField(default=0.0)),
                ('distribucion_sedes', models.JSONField(default=dict)),
                ('distribucion_carreras', models.JSONField(default=dict)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poll Analytics',
                'verbose_name_plural': 'Poll Analytics',
            },
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pollopcion',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='poll',
            name='anonima',
            field=models.BooleanField(default=False, help_text='Los votos son anónimos'),
        ),
        migrations.AddField(
            model_name='poll',
            name='carreras',
            field=models.JSONField(blank=True, default=list, help_text='Lista de carreras que pueden participar'),
        ),
        migrations.AddField(
            model_name='poll',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('archivada', 'Archivada')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='poll',
            name='inicia_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='poll',
            name='mostrar_resultados',
            field=models.CharField(choices=[('tiempo_real', 'Resultados en Tiempo Real'), ('al_cierre', 'Resultados al Cierre'), ('solo_moderador', 'Solo Visible para Moderadores')], default='tiempo_real', max_length=20),
        ),
        migrations.AddField(
            model_name='poll',
            name='requiere_justificacion',
            field=models.BooleanField(default=False, help_text='Requiere comentario al votar'),
        ),
        migrations.AddField(
            model_name='poll',
            name='sedes',
            field=models.ManyToManyField(blank=True, help_text='Sedes que pueden participar (todas si vacío)', to='campuses.sede'),
        ),
        migrations.AddField(
            model_name='poll',
            name='titulo',
            field=models.CharField(default='Encuesta sin título', max_length=200, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pollopcion',
            name='color',
            field=models.CharField(blank=True, help_text='Color hexadecimal para gráficos (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='pollopcion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la opción'),
        ),
        migrations.AddField(
            model_name='pollopcion',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='pollvoto',
            name='carrera_voto',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pollvoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pollvoto',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollvoto',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Comentario opcional del votante'),
        ),
        migrations.AddField(
            model_name='pollvoto',
            name='sede_voto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campuses.sede'),
        ),
        migrations.AddField(
            model_name='pollvoto',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='multi',
            field=models.BooleanField(default=False, help_text='Permite seleccionar múltiples opciones'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='forum.post'),
        ),
        migrations.AlterField(
            model_name='pollopcion',
            name='texto',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='pollopcion',
            unique_together={('poll', 'texto')},
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['estado', 'inicia_at'], name='polls_poll_estado_b58d74_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['creador', 'created_at'], name='polls_poll_creador_efb2df_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvoto',
            index=models.Index(fields=['poll', 'created_at'], name='polls_pollv_poll_id_2739cd_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvoto',
            index=models.Index(fields=['usuario', 'created_at'], name='polls_pollv_usuario_30120d_idx'),
        ),
        migrations.AddField(
            model_name='pollanalytics',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='polls.poll'),
        ),
    ]
