# Generated by Django 5.2.8 on 2025-11-29 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollanalytics_alter_poll_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('spam', 'Spam'), ('contenido_inapropiado', 'Contenido Inapropiado'), ('acoso', 'Acoso'), ('desinformacion', 'Desinformación'), ('violencia', 'Violencia'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado'), ('poll_eliminado', 'Encuesta Eliminada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='polls.poll')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_encuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Encuesta',
                'verbose_name_plural': 'Reportes de Encuestas',
                'unique_together': {('poll', 'usuario')},
            },
        ),
    ]
